-- 코드를 작성해주세요
SELECT C.ID
FROM ECOLI_DATA C
LEFT JOIN ECOLI_DATA P ON C.PARENT_ID = P.ID
LEFT JOIN ECOLI_DATA GP ON P.PARENT_ID = GP.ID
WHERE GP.PARENT_ID IS NULL AND GP.ID IS NOT NULL
ORDER BY C.ID ASC;