-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, 
        (P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as SALES_AMOUNT
      FROM OFFLINE_SALE
      GROUP BY PRODUCT_ID
     ) AS O ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;

