WITH TRUCK_RENTAL AS (
    -- 1단계 & 2단계: 트럭 대여 기록 정리 및 기간 카테고리 분류
    SELECT 
        H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL 
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

-- 3단계: 할인율 적용 및 최종 금액 계산
SELECT 
    T.HISTORY_ID,
    ROUND(T.DAILY_FEE * T.DURATION * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM TRUCK_RENTAL T
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON T.DURATION_TYPE = P.DURATION_TYPE 
    AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, T.HISTORY_ID DESC;