# SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
# FROM ITEM_INFO INFO
# JOIN ITEM_TREE TREE ON INFO.ITEM_ID = TREE.ITEM_ID
# WHERE TREE.PARENT_ITEM_ID IN (
#     SELECT ITEM_ID
#     FROM ITEM_INFO
#     WHERE RARITY = 'RARE'
# )
# ORDER BY INFO.ITEM_ID DESC;

SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO P
JOIN ITEM_TREE T ON P.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO C ON T.ITEM_ID = C.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC;