-- 코드를 입력하세요
SELECT
    DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY ON HISTORY.CAR_ID = CAR.CAR_ID
WHERE MONTH(HISTORY.START_DATE) = 10 AND CAR.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;