SELECT 
    SUM(GRADE.SCORE) AS SCORE, 
    EMP.EMP_NO,
    EMP.EMP_NAME,
    EMP.POSITION,
    EMP.EMAIL 
FROM HR_EMPLOYEES EMP
JOIN HR_GRADE GRADE ON EMP.EMP_NO = GRADE.EMP_NO
WHERE GRADE.YEAR = 2022
GROUP BY GRADE.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;