-- 코드를 입력하세요
SELECT 
    CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM (
    SELECT
        F.BOARD_ID, F.FILE_ID, F.FILE_NAME, F.FILE_EXT,
        RANK() OVER (ORDER BY B.VIEWS DESC) as rnk
    FROM USED_GOODS_FILE F
    JOIN USED_GOODS_BOARD B ON F.BOARD_ID = B.BOARD_ID
) AS ranked_files
WHERE rnk = 1
ORDER BY FILE_ID DESC;