-- 코드를 입력하세요
SELECT BOOK.CATEGORY, SUM(SALE.SALES) AS TOTAL_SALES
FROM BOOK
JOIN BOOK_SALES SALE ON SALE.BOOK_ID = BOOK.BOOK_ID
WHERE SALE.SALES_DATE LIKE '2022-01%'
GROUP BY BOOK.CATEGORY
ORDER BY CATEGORY ASC;
